### ISSUE TITLE
lenstronomy dependency requires numba <= 0.58.1 

### ISSUE THREAD

**Issue by Ferr013** [ajshajib/dolphin#43]
Lenstronomy requires `numba.decorated_jit`, which is [deprecated and removed from `numba version>=0.59.0`](https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit).
I suggest adding `numba <= 0.58.1` in the [requirements.txt](https://github.com/ajshajib/dolphin/blob/master/requirements.txt).
In addition, `numba version= 0.58.1` requires also to have `python<3.12.`

**Comment by sibirrer** [comment]
@Ferr013 are you sure the latest version of lenstronomy still required numba.decorated_jit? I thought I had removed it, but let me know in case. Otherwise, please make an issue on lenstronomy as well such that we can update it there as well. Thank you!

**Comment by ajshajib** [comment]
Hi @Ferr013, thanks a lot for pointing out the version incompatibilities. Have you checked that the current requirement `lenstronomy<=1.11.5` does not automatically satisfy your version suggestions for `numba` and `python`?

**Comment by Ferr013** [comment]
Hi @sibirrer and @ajshajib, I tried to install dolphin on a fresh conda environment (python == 3.12.4).
The installation works fine, but when I run `from dolphin.processor import Processor` I get the following error:
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/b4c71adb-df56-4e2d-aa4e-67d4a0face8a">
`lenstronomy<=1.11.5` does not seem sufficient in this case.

**Comment by sibirrer** [comment]
@Ferr013 I can't really talk about older lenstronomy versions. Perhaps @ajshajib has a particular reason to keep an older version of lenstronomy running. Generally, my recommendation is to upgrade to the latest version to avoid (too) many of these deprecation errors.

**Comment by ajshajib** [comment]
@sibirrer, It's simply that `dolphin` didn't receive update it `lenstronomy` compatibility since the Dinos-I paper, since there has been no active project making use of it. But, in general, it would indeed to necessary to keep it updated to be compatible with the latest `lenstronomy` to avoid such issues.

**Comment by ajshajib** [comment]
Hi @Ferr013, I have updated `dolphin` with #48 so that it is compatible with the latest `lenstronomy`. So, if you meet all the dependency version requirements for `lenstronomy`, `dolphin` is expected to run without error. If the dependency version is an issue particularly on `lenstronomy`'s side, then please make an issue in `lenstronomy`'s repo for it to be resolved there, as @sibirrer suggested above. This should also apply to the other issue, #44.

**Comment by Ferr013** [comment]
Thanks @ajshajib

**Comment by ajshajib** [comment]
@Ferr013, if you are not having these issues anymore on the `dolphin` side after the latest updates, please close the issue(s). But if they still persist, please let me know.

**Comment by Ferr013** [comment]
Hi @ajshajib, there are some issues with the new version: 
I am testing the basic example, and when I run `processor.swim()` I get `ValueError: Sampler 'MCMC' not supported! Supported ones are: ['emcee']
`
<img width="1155" alt="Screenshot 2024-09-05 at 10 12 08 AM" src="https://github.com/user-attachments/assets/8d1d8c6a-3c1c-4eff-92d6-c0d464a453a1">

The old version `09279f0` works:
<img width="1142" alt="Screenshot 2024-09-05 at 10 12 29 AM" src="https://github.com/user-attachments/assets/c1ed5550-791f-4950-8026-d3b767be4331">

I think `dolphin.__version__` always reads`0.0.0` because the version in the folder `dolphin/dolphin/__init__.py` is not updated.

I attach full error dump below:
<img width="1101" alt="Screenshot 2024-09-05 at 10 20 28 AM" src="https://github.com/user-attachments/assets/65c4627e-39b4-4354-bac9-d2370288e020">
<img width="1101" alt="Screenshot 2024-09-05 at 10 20 37 AM" src="https://github.com/user-attachments/assets/fad9208c-0de4-4600-8267-88654c8dc79b">

**Comment by ajshajib** [comment]
Hi @Ferr013, thanks for looking into the updated version. To fix the error, you can simply replace "MCMC" with "emcee" in the config file. Although "MCMC" is still a supported keyword in `lenstronomy` for backward-compatibility, it will default to "emcee". However, I wanted to make the user of `dolphin` to be explicitly aware of using "emcee" because the sampler setting keywords (`walkerRatio`, etc.) are particular to `emcee`.

I have updated the version number in the __init__ file, thanks for catching this.

**Comment by Ferr013** [comment]
Hi @ajshajib, sorry I should have used the latest example. Everything works now, I'll close the issue!
